packageExtensions:
  "@yarnpkg/plugin-npm@*":
    dependencies:
      "@yarnpkg/cli": "*"
      "@yarnpkg/plugin-pack": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.0.0.cjs
